name: Archive Files
on:
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create archive
        run: python -m parenttext_pipeline.archive
      - name: Publish output folder
        uses: actions/upload-artifact@v3
        with:
          name: Archive Files
          path: output
